# -*- coding: utf-8 -*-
"""LAB1_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tUk-LoRkUljpJMxegmJz8lvw23OG5L4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

iris_dataset = pd.read_csv('/content/drive/MyDrive/TY /SEM6/DL_Lab/Iris.csv')

"""#Check dimensions"""

iris_dataset.head()

iris_dataset.shape

iris_dataset.info()

"""#Check and Hndle missing values"""

iris_dataset.isnull()

iris_dataset.isnull().sum()

iris_dataset.describe()

"""#Plots and Visualization

"""

plt.figure(figsize=(10,6))
sns.boxplot(data=iris_dataset.drop('Species', axis=1))
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(iris_dataset.drop('Species', axis=1), annot=True, cmap='viridis', linewidths=.5)
plt.show()

sns.pairplot(iris_dataset, hue ='Species')
plt.show()

"""#Handling Outliers"""

Q1 = iris_dataset.iloc[:, :-1].quantile(0.25)
Q3 = iris_dataset.iloc[:, :-1].quantile(0.75)
IQR = Q3 - Q1

outliers = ((iris_dataset.iloc[:, :-1] < (Q1 - 1.5 * IQR)) |
            (iris_dataset.iloc[:, :-1] > (Q3 + 1.5 * IQR)))

outliers.sum()

iris_dataset_no_outliers = iris_dataset[~outliers.any(axis=1)]
iris_dataset_no_outliers.shape